Update Dockerfile

diff --git a/deploy/backend-gpu/Dockerfile b/deploy/backend-gpu/Dockerfile
--- a/deploy/backend-gpu/Dockerfile
+++ b/deploy/backend-gpu/Dockerfile
@@ -6,7 +6,8 @@ ARG MLVALIDATION
 ARG IMAGE_TAG
 ENV IMAGE_TAG ${IMAGE_TAG}
 
-RUN apt-get update && apt-get install nvidia-modprobe -y
+# Debugging: Ensure dlib is installed
+RUN python -m pip show dlib || echo "dlib not found"
 
 WORKDIR /code
 RUN git clone --depth 1 https://github.com/LibrePhotos/librephotos .
